Imports PLCcom.Opc.Ua
Imports PLCcom.Opc.Ua.Server.Sdk
Imports System
Imports System.Collections.Generic

' ==============================================================================
' PLCcom OPC UA Server SDK - Workshop 51: Logging
'
' The SDK exposes the OPC UA stack's internal trace messages through the
' LogMessage event. This lets you route SDK diagnostics to your own
' logging framework (NLog, Serilog, Microsoft.Extensions.Logging, etc.)
'
' Log levels (from least to most verbose):
'   Error   -> only errors that affect functionality
'   Warning -> errors + warnings (recommended for production)
'   Info    -> errors + warnings + service calls (connect, read, write, subscribe)
'   Debug   -> everything including internal stack details (very verbose)
'
' What you will learn:
'   * How to subscribe to SDK log messages
'   * How to set the log verbosity level
'   * How to filter and format log messages
'   * How to route logs to your own framework
'
' Connect with any OPC UA client to: opc.tcp://localhost:48450
' ==============================================================================

Module Program

    Sub Main(args As String())

        ' -- License -----------------------------------------------------------
        ' TODO: Submit your license information from your license e-mail
        Dim LicenseUserName As String = "<Enter your UserName here>"
        Dim LicenseSerial As String = "<Enter your Serial here>"

        Console.WriteLine("╔══════════════════════════════════════════════════════════════╗")
        Console.WriteLine("║  PLCcom OPC UA Server SDK - Workshop 51: Logging             ║")
        Console.WriteLine("║                                                              ║")
        Console.WriteLine("║  This example demonstrates:                                  ║")
        Console.WriteLine("║  * Subscribing to SDK log messages                           ║")
        Console.WriteLine("║  * Setting log verbosity (Error, Warning, Info, Debug)       ║")
        Console.WriteLine("║  * Filtering log messages by level                           ║")
        Console.WriteLine("║  * Routing logs to your own framework                        ║")
        Console.WriteLine("╚══════════════════════════════════════════════════════════════╝")
        Console.WriteLine()

        Dim config As New UaServerConfiguration With {
            .ApplicationName = "PLCcom Workshop 51 - Logging",
            .ApplicationUri = "urn:localhost:PLCcom:Workshop:51",
            .ProductUri = "https://www.indi-an.com/en/plccom/opc-ua-sdk/opcua-overview/",
            .BaseAddresses = New List(Of String) From {"opc.tcp://localhost:48450"},
            .SecurityPolicies = UaServer.GetRecommendedSecurityPolicies(),
            .UserTokenPolicies = New List(Of UserTokenPolicy) From {
                New UserTokenPolicy With {.TokenType = UserTokenType.Anonymous}
            },
            .CertificateStorePath = ".\pki"
        }

        Using server As New UaServer(LicenseUserName, LicenseSerial)
            AddHandler server.CertificateValidation, Sub(s, e) e.Accept = True

            ' -- Subscribe to log messages -------------------------------------
            ' The LogMessage event fires for every message that passes the current log level.
            ' Subscribe BEFORE calling Start() to capture startup messages.
            ' In production, replace Console.WriteLine with your logging framework call.
            AddHandler server.LogMessage, Sub(sender, e)
                ' Color-code by severity for easy reading in the console
                Select Case e.Level
                    Case UaLogLevel.Error
                        Console.ForegroundColor = ConsoleColor.Red
                    Case UaLogLevel.Warning
                        Console.ForegroundColor = ConsoleColor.Yellow
                    Case UaLogLevel.Info
                        Console.ForegroundColor = ConsoleColor.Cyan
                    Case Else
                        Console.ForegroundColor = ConsoleColor.Gray ' Debug
                End Select

                Console.WriteLine($"  [{e.Level,-7}] {e.Message}")
                Console.ResetColor()

                ' Example: forward to your logging framework
                ' logger.Log(e.Level, e.Message, e.Exception)
            End Sub

            ' -- Set log level -------------------------------------------------
            ' SetLogLevel() controls which messages are generated by the OPC UA stack.
            ' Call this before Start() to capture startup messages at the desired level.
            '   Error   -> only errors (minimal output, good for production)
            '   Warning -> errors + warnings
            '   Info    -> errors + warnings + service calls (good for development)
            '   Debug   -> everything (very verbose, use only for troubleshooting)
            server.SetLogLevel(UaLogLevel.Info)

            Console.WriteLine("  Log level set to: Info")
            Console.WriteLine("  (connect a client to see log messages appear here)")
            Console.WriteLine()

            Console.Write("Starting server ... ")
            Try
                server.Start(config)
            Catch ex As Exception
                Console.WriteLine("FAILED")
                Console.WriteLine(ex.Message)
                Console.ReadLine()
                Return
            End Try
            Console.WriteLine("OK")
            Console.WriteLine()

            Dim plant = server.CreateFolder("Plant")
            server.CreateVariable(Of Double)(plant, "Temperature", initialValue:=22.0)

            Console.WriteLine("╔══════════════════════════════════════════════════════════════╗")
            Console.WriteLine("║  Server is running with logging enabled.                     ║")
            Console.WriteLine("║                                                              ║")
            Console.WriteLine("║  Endpoint: opc.tcp://localhost:48450                         ║")
            Console.WriteLine("║                                                              ║")
            Console.WriteLine("║  Try:                                                        ║")
            Console.WriteLine("║  * Connect a client - see the session creation log entry     ║")
            Console.WriteLine("║  * Read Temperature - see the Read service log entry         ║")
            Console.WriteLine("║  * Subscribe to Temperature - see subscription log entries   ║")
            Console.WriteLine("║  * Disconnect - see the session close log entry              ║")
            Console.WriteLine("║                                                              ║")
            Console.WriteLine("║  Press ENTER to exit.                                        ║")
            Console.WriteLine("╚══════════════════════════════════════════════════════════════╝")
            Console.ReadLine()

        End Using

    End Sub

End Module
